system:
  mass1: 10.0
  mass2: 20.0
  length1: 1.5
  length2: 1.0
  gravity: 9.81

initial_conditions:
  theta1: 90.0
  omega1: 0.0
  theta2: 270.0
  omega2: 0.0
  angle_units: deg

time_integration:
  time_step: 0.01

simulation:
  time_end: 20.0